# https://taskfile.dev
version: "3"

tasks:
  default:
    deps: [test]

  bootstrap:
    generates:
      - Brewfile.lock.json
    cmds:
      - brew bundle

  fix:
    deps: [bootstrap]
    cmds:
      - prettier --write --list-different --ignore-unknown .
      - markdownlint --fix .

  test:
    deps: [bootstrap]
    cmds:
      - prettier --check --ignore-unknown .
      - |
        act pull_request \
          --secret GITHUB_TOKEN="$(gh auth token)"  \
          --container-architecture linux/amd64
